services:

  # Запуск MySQL
  mysql:
    image: mysql:5.7
    container_name: $MYSQL_CONTAINER_NAME
    ports:
      - $MYSQL_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_LOGIN
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - $DATA_PATH/mysql:/var/lib/mysql

  # Запуск PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: $POSTGRES_CONTAINER_NAME
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_LOGIN
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    volumes:
      - $DATA_PATH/postgresql:/var/lib/postgresql/data

  # Запуск TimeScaleDb
  timescale:
    image: timescale/timescaledb:2.13.0-pg14
    container_name: $TIMESCALE_CONTAINER_NAME
    ports:
      - $TIMESCALE_PORT:5432
    environment:
      POSTGRES_USER: $TIMESCALE_LOGIN
      POSTGRES_PASSWORD: $TIMESCALE_PASSWORD
      POSTGRES_DB: $TIMESCALE_DATABASE
    volumes:
      - $DATA_PATH/timescale:/var/lib/postgresql/data

  # Запуск Redis
  redis:
    image: redis:7.2-alpine
    container_name: $REDIS_CONTAINER_NAME
    ports:
      - $REDIS_PORT:6379
    volumes:
      - $DATA_PATH/redis:/data
    command:
      - redis-server
      - --requirepass
      - $REDIS_PASSWORD
      - --save
      - "900"
      - "1"
      - --loglevel
      - warning

  # Запуск RabbitMq
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: $RABBITMQ_CONTAINER_NAME
    ports:
      - "$RABBITMQ_PORT:5672"
      - "$RABBITMQ_ADMIN_PORT:15672"
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USERNAME
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    volumes:
      - $DATA_PATH/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
